In [1]:
import numpy as np

In [3]:
arr = np.arange(1,101)

In [4]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

2. 
1부터 100까지(1과 100 포함) 중 3의 배수만 담겨 있는 numpy array를 생성하고 출력해 주세요.



In [16]:
arr2 = np.arange(3,101,3)

In [18]:
arr2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
arr2^2

array([ 1,  4, 11, 14, 13, 16, 23, 26, 25, 28, 35, 38, 37, 40, 47, 50, 49,
       52, 59, 62, 61, 64, 71, 74, 73, 76, 83, 86, 85, 88, 95, 98, 97],
      dtype=int32)

흥부부대찌개 가맹점
엔화로 저장한 매출 데이터로 원화로 변환하는 작업이 필요
1엔에 10.08원, 원화 매출이 담긴 numpy array 만들어 출력하시오

list안의 값을 numpy 로 ?
     **arr = np.array(list)

In [34]:
arr2 > 10

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [35]:
booleans = np.array([True, True ,False, True, False])

In [37]:
np.where(booleans)

(array([0, 1, 3], dtype=int64),)

In [40]:
np.where(arr2> 30)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32], dtype=int64),)

In [46]:
filter = np.where(arr2 > 30)
filter

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32], dtype=int64),)

In [47]:
arr2[filter]

array([33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81,
       84, 87, 90, 93, 96, 99])