In [2]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]



In [5]:
# 코드를 작성하세요.
array = np.array(revenue_in_yen)
array

array([300000, 340000, 320000, 360000, 440000, 140000, 180000, 340000,
       330000, 290000, 280000, 380000, 170000, 140000, 230000, 390000,
       400000, 350000, 380000, 150000, 110000, 240000, 380000, 380000,
       340000, 420000, 150000, 130000, 360000, 320000, 250000])

In [7]:
filter =np.where(array < 200000)
filter

(array([ 5,  6, 12, 13, 19, 20, 26, 27], dtype=int64),)

In [8]:
bad_days_revenue = array[filter]



In [9]:
# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])